language: java

jdk: oraclejdk11

services:
  - postgresql

addons:
  postgresql: "10.5"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn sonar:sonar -Dsonar.projectKey=Geodezist_auto-solver -Dsonar.organization=geodezist-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
