language: java

jdk: oraclejdk9

services:
  - postgresql

addons:
  postgresql: "10.5"
  sonarcloud:
    organization: "geodezist-github"
    token:
      secure: $SONAR_TOKEN

after_success:
  - bash <(curl -s https://codecov.io/bash)
