spring:
  application:
    name: auto-solver

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: autosolver
    password: autosolver
    platform: postgresql
    initialization-mode: always

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  liquibase:
    change-log: classpath:liquibase/master.yml

logging:
  level:
    org.springframework.*: info
